### ISSUE TITLE
generate_access_token can't use service_account_path format

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/python-iam#18]
According to the docstring for `generate_access_token`, `service_account_path` can be used to build the required format for a service account:
```python
client = iam_credentials_v1.IAMCredentialsClient()
name = client.service_account_path('[PROJECT]', '[SERVICE_ACCOUNT]')
scope = []
response = client.generate_access_token(name, scope)
```

But `service_account_path` returns a format that the IAM API doesn't accept:

```python
>>> print(name)
projects/[PROJECT]/serviceAccounts/[SERVICE_ACCOUNT]
```

The correct format is: `projects/-/serviceAccounts/[ACCOUNT_EMAIL_OR_UNIQUEID]`  I don't know if all service account API endpoints accept this format.

**Comment by busunkim96** [comment]
The path generated by the library seems to match up with the API definition. See [the proto file](https://github.com/googleapis/googleapis/blob/57e72ebf709dc5ebbd27a746d6b92b05c054dea2/google/iam/credentials/v1/iamcredentials.proto#L43-L48). 

Is the API returning an error if you use the path from `client.service_account_path`?

**Comment by rvandegrift** [comment]
Yes, I get a 400 Bad Request.  You should be able to reproduce by running the example code (you'll need to fill in an actual scope, project, and service account).

Could the proto file be wrong?  The docstring for `generate_access_token` says this:
```
Args:
    name (str): Required. The resource name of the service account for which the
        credentials are requested, in the following format:
        ``projects/-/serviceAccounts/{ACCOUNT_EMAIL_OR_UNIQUEID}``. The ``-``
        wildcard character is required; replacing it with a project ID is
        invalid.
```
That matches the language from the discovery document for iamcredentials.

**Comment by busunkim96** [comment]
Ah I see, it looks like that docstring is coming from https://github.com/googleapis/googleapis/blob/57e72ebf709dc5ebbd27a746d6b92b05c054dea2/google/iam/credentials/v1/common.proto#L36-L45

If you pass '-' for project manually the helper method will produce the correct path. That said, it isn't ideal that the method accepts project when it must always be '-'.

```py
client.service_account_path('-', '[SERVICE_ACCOUNT')
```

**Comment by busunkim96** [comment]
Hi,

I checked with the some other folks, and it looks like passing `-` to the method is the correct thing to do here. The API owners may support passing projects in the future, so we want to leave the possibility open in the pattern.
