### ISSUE TITLE
Code snippets for IAM deny policies should wait for LROs to complete

### ISSUE THREAD

**Issue by hegemonic** [googleapis/python-iam#238]
The IAM v2 API provides support for deny policies. Most methods in the IAM v2 API return long-running operations (LROs).

In the code snippets for the Go, Java, and Node.js client libraries for IAM v2, we wait for the LRO to complete, then print information about the result of the LRO. See these examples for creating a deny policy:

+ [Go](https://github.com/GoogleCloudPlatform/golang-samples/blob/8f94c6d4ddbc6a18094f8b597121294fa71a9e98/iam/deny/create_deny_policy.go#L118-L128)
+ [Java](https://github.com/googleapis/java-iam/blob/63a136b56dff577ac1e630293c80bd10539c1930/samples/cloud-client/snippets/src/main/java/CreateDenyPolicy.java#L143-L160)
+ [Node.js](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/2acefcbe2c4d71669b6a28d075312076a17a5fee/iam/deny/createDenyPolicy.js#L97-L100)

In contrast, the Python code snippets ignore [the `Operation` that's returned](https://github.com/googleapis/python-iam/blob/b8475f0f57d8b18e05f22163e30455735324681d/google/cloud/iam_v2beta/services/policies/client.py#L717-L723) and say that the operation is complete, even though it might not be. See [this example](https://github.com/googleapis/python-iam/blob/b8475f0f57d8b18e05f22163e30455735324681d/samples/snippets/create_deny_policy.py#L104-L105).

We should update the Python snippets to handle LROs just like the snippets for other languages.

@Sita04 FYI.

**Comment by Sita04** [comment]
Thanks for the catch! 
Will be fixed by this commit: https://github.com/googleapis/python-iam/pull/230/commits/38ab3098b05ab27ff43df79fc28919f39dd408da

**Comment by Sita04** [comment]
Closing the issue as the samples are fixed.
